import { Product, Category, Brand, Banner, Order, User, Address, Coupon } from '@/types';

// Categories
export const MOCK_CATEGORIES: Category[] = [
  { id: '1', name: 'Fruits & Vegetables', icon: '🍎', productCount: 45 },
  { id: '2', name: 'Dairy & Eggs', icon: '🥛', productCount: 32 },
  { id: '3', name: 'Bakery & Snacks', icon: '🍞', productCount: 28 },
  { id: '4', name: 'Beverages', icon: '🥤', productCount: 38 },
  { id: '5', name: 'Meat & Seafood', icon: '🍖', productCount: 22 },
  { id: '6', name: 'Frozen Foods', icon: '🧊', productCount: 35 },
  { id: '7', name: 'Personal Care', icon: '🧴', productCount: 42 },
  { id: '8', name: 'Household', icon: '🧹', productCount: 30 },
  { id: '9', name: 'Baby Care', icon: '👶', productCount: 18 },
  { id: '10', name: 'Pet Care', icon: '🐕', productCount: 15 },
];

// Brands
export const MOCK_BRANDS: Brand[] = [
  { id: '1', name: 'Amul', productCount: 25 },
  { id: '2', name: 'Britannia', productCount: 18 },
  { id: '3', name: 'Coca-Cola', productCount: 12 },
  { id: '4', name: 'Haldiram\'s', productCount: 20 },
  { id: '5', name: 'Parle', productCount: 15 },
  { id: '6', name: 'Dabur', productCount: 22 },
  { id: '7', name: 'Nestle', productCount: 28 },
  { id: '8', name: 'ITC', productCount: 16 },
  { id: '9', name: 'HUL', productCount: 30 },
  { id: '10', name: 'Patanjali', productCount: 14 },
];

// Products
export const MOCK_PRODUCTS: Product[] = [
  // Fruits & Vegetables
  {
    id: 'p1',
    name: 'Fresh Red Apples',
    description: 'Premium quality red apples, crisp and sweet. Rich in fiber and antioxidants.',
    price: 180,
    originalPrice: 220,
    discount: 18,
    image: 'https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=400',
    categoryId: '1',
    brandId: '1',
    brand: 'Fresh Farm',
    category: 'Fruits & Vegetables',
    inStock: true,
    stockQuantity: 50,
    unit: 'kg',
    minQuantity: 0.5,
    maxQuantity: 10,
    ingredients: ['Apples'],
    nutrition: {
      calories: 52,
      protein: 0.3,
      carbs: 14,
      fat: 0.2,
      fiber: 2.4,
      sugar: 10,
    },
    rating: 4.5,
    reviewCount: 234,
    tags: ['organic', 'fresh'],
  },
  {
    id: 'p2',
    name: 'Bananas - Bunch',
    description: 'Ripe yellow bananas, perfect for daily nutrition. High in potassium.',
    price: 45,
    image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400',
    categoryId: '1',
    brandId: '1',
    brand: 'Fresh Farm',
    category: 'Fruits & Vegetables',
    inStock: true,
    stockQuantity: 30,
    unit: 'dozen',
    minQuantity: 1,
    maxQuantity: 5,
    rating: 4.3,
    reviewCount: 189,
  },
  {
    id: 'p3',
    name: 'Fresh Tomatoes',
    description: 'Farm-fresh red tomatoes, perfect for cooking and salads.',
    price: 60,
    image: 'https://images.unsplash.com/photo-1546097491-8c5c5e5b5b5b?w=400',
    categoryId: '1',
    brandId: '1',
    brand: 'Fresh Farm',
    category: 'Fruits & Vegetables',
    inStock: true,
    stockQuantity: 40,
    unit: 'kg',
    minQuantity: 0.5,
    maxQuantity: 10,
    rating: 4.2,
    reviewCount: 156,
  },
  // Dairy & Eggs
  {
    id: 'p4',
    name: 'Amul Full Cream Milk',
    description: 'Pure, fresh full cream milk. Rich in calcium and protein.',
    price: 66,
    image: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400',
    categoryId: '2',
    brandId: '1',
    brand: 'Amul',
    category: 'Dairy & Eggs',
    inStock: true,
    stockQuantity: 100,
    unit: 'L',
    minQuantity: 0.5,
    maxQuantity: 5,
    nutrition: {
      calories: 61,
      protein: 3.2,
      carbs: 4.8,
      fat: 3.3,
      servingSize: '100ml',
    },
    rating: 4.6,
    reviewCount: 456,
  },
  {
    id: 'p5',
    name: 'Farm Fresh Eggs - Pack of 12',
    description: 'Farm fresh eggs, rich in protein and essential nutrients.',
    price: 120,
    image: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=400',
    categoryId: '2',
    brandId: '1',
    brand: 'Farm Fresh',
    category: 'Dairy & Eggs',
    inStock: true,
    stockQuantity: 60,
    unit: 'pack',
    minQuantity: 1,
    maxQuantity: 10,
    rating: 4.7,
    reviewCount: 312,
  },
  {
    id: 'p6',
    name: 'Amul Butter - 500g',
    description: 'Pure, creamy butter made from fresh cream. Perfect for cooking and spreading.',
    price: 285,
    image: 'https://images.unsplash.com/photo-1589985270826-4b7fe135a9c4?w=400',
    categoryId: '2',
    brandId: '1',
    brand: 'Amul',
    category: 'Dairy & Eggs',
    inStock: true,
    stockQuantity: 25,
    unit: 'pack',
    minQuantity: 1,
    maxQuantity: 5,
    rating: 4.8,
    reviewCount: 567,
  },
  // Bakery & Snacks
  {
    id: 'p7',
    name: 'Britannia Bread - White',
    description: 'Soft, fresh white bread. Perfect for breakfast and sandwiches.',
    price: 45,
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400',
    categoryId: '3',
    brandId: '2',
    brand: 'Britannia',
    category: 'Bakery & Snacks',
    inStock: true,
    stockQuantity: 80,
    unit: 'pack',
    minQuantity: 1,
    maxQuantity: 10,
    rating: 4.4,
    reviewCount: 289,
  },
  {
    id: 'p8',
    name: 'Haldiram\'s Namkeen Mix',
    description: 'Crispy, spicy namkeen mix. A perfect snack for any time.',
    price: 95,
    originalPrice: 120,
    discount: 21,
    image: 'https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=400',
    categoryId: '3',
    brandId: '4',
    brand: 'Haldiram\'s',
    category: 'Bakery & Snacks',
    inStock: true,
    stockQuantity: 45,
    unit: 'pack',
    minQuantity: 1,
    maxQuantity: 10,
    rating: 4.5,
    reviewCount: 423,
  },
  {
    id: 'p9',
    name: 'Parle-G Glucose Biscuits',
    description: 'Classic glucose biscuits. Energy for everyone.',
    price: 25,
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400',
    categoryId: '3',
    brandId: '5',
    brand: 'Parle',
    category: 'Bakery & Snacks',
    inStock: true,
    stockQuantity: 120,
    unit: 'pack',
    minQuantity: 1,
    maxQuantity: 20,
    rating: 4.6,
    reviewCount: 890,
  },
  // Beverages
  {
    id: 'p10',
    name: 'Coca-Cola - 2L',
    description: 'Refreshing cola drink. Perfect for parties and gatherings.',
    price: 95,
    image: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=400',
    categoryId: '4',
    brandId: '3',
    brand: 'Coca-Cola',
    category: 'Beverages',
    inStock: true,
    stockQuantity: 70,
    unit: 'bottle',
    minQuantity: 1,
    maxQuantity: 10,
    rating: 4.3,
    reviewCount: 234,
  },
  {
    id: 'p11',
    name: 'Tropicana Orange Juice - 1L',
    description: '100% pure orange juice. Rich in Vitamin C.',
    price: 180,
    originalPrice: 220,
    discount: 18,
    image: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400',
    categoryId: '4',
    brandId: '7',
    brand: 'Nestle',
    category: 'Beverages',
    inStock: true,
    stockQuantity: 35,
    unit: 'bottle',
    minQuantity: 1,
    maxQuantity: 5,
    rating: 4.4,
    reviewCount: 178,
  },
  {
    id: 'p12',
    name: 'Red Label Tea - 500g',
    description: 'Premium quality tea leaves. Rich aroma and flavor.',
    price: 245,
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400',
    categoryId: '4',
    brandId: '9',
    brand: 'HUL',
    category: 'Beverages',
    inStock: true,
    stockQuantity: 50,
    unit: 'pack',
    minQuantity: 1,
    maxQuantity: 5,
    rating: 4.5,
    reviewCount: 345,
  },
  // Out of stock example
  {
    id: 'p13',
    name: 'Premium Basmati Rice - 5kg',
    description: 'Long grain basmati rice. Perfect for biryani and pulao.',
    price: 450,
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400',
    categoryId: '1',
    brandId: '8',
    brand: 'ITC',
    category: 'Fruits & Vegetables',
    inStock: false,
    stockQuantity: 0,
    unit: 'pack',
    minQuantity: 1,
    maxQuantity: 5,
    rating: 4.6,
    reviewCount: 234,
  },
  // More products
  {
    id: 'p14',
    name: 'Dabur Honey - 500g',
    description: 'Pure, natural honey. Rich in antioxidants and nutrients.',
    price: 285,
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400',
    categoryId: '7',
    brandId: '6',
    brand: 'Dabur',
    category: 'Personal Care',
    inStock: true,
    stockQuantity: 40,
    unit: 'bottle',
    minQuantity: 1,
    maxQuantity: 5,
    rating: 4.7,
    reviewCount: 567,
  },
  {
    id: 'p15',
    name: 'Maggi Noodles - Pack of 4',
    description: 'Instant noodles. Ready in 2 minutes.',
    price: 56,
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400',
    categoryId: '3',
    brandId: '7',
    brand: 'Nestle',
    category: 'Bakery & Snacks',
    inStock: true,
    stockQuantity: 90,
    unit: 'pack',
    minQuantity: 1,
    maxQuantity: 20,
    rating: 4.2,
    reviewCount: 1234,
  },
];

// Banners
export const MOCK_BANNERS: Banner[] = [
  {
    id: 'b1',
    title: 'Fresh Fruits & Vegetables',
    image: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=800',
    categoryId: '1',
  },
  {
    id: 'b2',
    title: 'Dairy Products Sale',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=800',
    categoryId: '2',
  },
  {
    id: 'b3',
    title: 'Snacks & Beverages',
    image: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800',
    categoryId: '3',
  },
];

// Mock User
export const MOCK_USER: User = {
  id: 'u1',
  name: 'John Doe',
  email: 'john.doe@example.com',
  phone: '+91 9876543210',
  addresses: [
    {
      id: 'a1',
      type: 'home',
      name: 'John Doe',
      phone: '+91 9876543210',
      addressLine1: '123, Main Street',
      addressLine2: 'Near City Mall',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400001',
      landmark: 'Opposite Bank',
      isDefault: true,
    },
  ],
  isVerified: true,
  createdAt: '2024-01-15',
};

// Mock Orders
export const MOCK_ORDERS: Order[] = [
  {
    id: 'o1',
    orderNumber: 'ORD-2024-001',
    userId: 'u1',
    items: [
      {
        id: 'ci1',
        productId: 'p1',
        product: MOCK_PRODUCTS[0],
        quantity: 2,
        price: 180,
        total: 360,
      },
      {
        id: 'ci2',
        productId: 'p4',
        product: MOCK_PRODUCTS[3],
        quantity: 2,
        price: 66,
        total: 132,
      },
    ],
    subtotal: 492,
    deliveryFee: 40,
    discount: 50,
    total: 482,
    status: 'delivered',
    paymentMethod: 'upi',
    paymentStatus: 'completed',
    address: MOCK_USER.addresses[0],
    placedAt: '2024-01-20T10:30:00Z',
    deliveredAt: '2024-01-21T14:20:00Z',
    tracking: [
      { status: 'confirmed', timestamp: '2024-01-20T10:35:00Z', message: 'Order confirmed' },
      { status: 'processing', timestamp: '2024-01-20T11:00:00Z', message: 'Order being processed' },
      { status: 'packed', timestamp: '2024-01-20T15:30:00Z', message: 'Order packed and ready' },
      { status: 'shipped', timestamp: '2024-01-21T09:00:00Z', message: 'Order shipped' },
      { status: 'out_for_delivery', timestamp: '2024-01-21T12:00:00Z', message: 'Out for delivery' },
      { status: 'delivered', timestamp: '2024-01-21T14:20:00Z', message: 'Order delivered' },
    ],
  },
  {
    id: 'o2',
    orderNumber: 'ORD-2024-002',
    userId: 'u1',
    items: [
      {
        id: 'ci3',
        productId: 'p7',
        product: MOCK_PRODUCTS[6],
        quantity: 3,
        price: 45,
        total: 135,
      },
    ],
    subtotal: 135,
    deliveryFee: 40,
    discount: 0,
    total: 175,
    status: 'out_for_delivery',
    paymentMethod: 'cod',
    paymentStatus: 'pending',
    address: MOCK_USER.addresses[0],
    placedAt: '2024-01-22T08:15:00Z',
    estimatedDelivery: '2024-01-22T18:00:00Z',
    tracking: [
      { status: 'confirmed', timestamp: '2024-01-22T08:20:00Z', message: 'Order confirmed' },
      { status: 'processing', timestamp: '2024-01-22T09:00:00Z', message: 'Order being processed' },
      { status: 'packed', timestamp: '2024-01-22T11:30:00Z', message: 'Order packed and ready' },
      { status: 'out_for_delivery', timestamp: '2024-01-22T14:00:00Z', message: 'Out for delivery' },
    ],
  },
];

// Coupons
export const MOCK_COUPONS: Coupon[] = [
  {
    id: 'c1',
    code: 'WELCOME50',
    title: 'Welcome Offer',
    description: 'Get ₹50 off on orders above ₹500',
    discountType: 'fixed',
    discountValue: 50,
    minOrderValue: 500,
    validFrom: '2024-01-01',
    validUntil: '2024-12-31',
    isActive: true,
  },
  {
    id: 'c2',
    code: 'SAVE20',
    title: '20% Off',
    description: 'Get 20% off on orders above ₹1000',
    discountType: 'percentage',
    discountValue: 20,
    minOrderValue: 1000,
    maxDiscount: 200,
    validFrom: '2024-01-01',
    validUntil: '2024-12-31',
    isActive: true,
  },
];

